# Environment variables
export SXHKD_SHELL="bash"
export GPG_TTY=$(tty)
export WLR_NO_HARDWARE_CURSORS=1

# Aliases
alias la='ls -a'
alias ll='ls -l'

# Shell jobs
(cat ~/.cache/wal/sequences &)

# Direnv
eval "$(direnv hook bash)"
